# Generated by Skyramp v1.3.12 on 2026-03-14 04:52:34.699913467 +0000 UTC m=+220.344838853
# Command: skyramp generate fuzz rest http://localhost:8000/items/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_items_post_category_fuzz.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"Gadget Pro","description":"A premium electronics gadget","price":99.99,"tax":9.99,"category":"electronics"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /items/ POST
def test_items_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    items_POST_request_body = r'''{
      "name": "Gadget Pro",
      "description": "A premium electronics gadget",
      "price": 99.99,
      "tax": 9.99,
      "category": "electronics"
    }'''
    
    # Fuzz strategies
    items_post_fuzzed_body = {
        "category": "0123456789",
        "description": "0123456789",
        "name": "0123456789",
        "price": -10,
        "tax": -10
    }
    # Fuzz status codes
    expected_items_post_status_code = {
        "category": "40x",
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }
    # Fuzz status codes for Null values
    expected_items_post_null_status_code = {
        "category": "40x",
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }

    # Execute Request
    items_POST_response = client.send_request(
        url=URL,
        path="/items/",
        method="POST",
        body=items_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(items_post_fuzzed_body):
        # Execute Request
        items_POST_response = client.send_request(
            url=URL,
            path="/items/",
            method="POST",
            body=items_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(items_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_items_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(items_post_fuzzed_body, key) }'
        )

        # Execute Request
        items_POST_response = client.send_request(
            url=URL,
            path="/items/",
            method="POST",
            body=items_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_items_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_items_post()
