# Generated by Skyramp v1.3.12 on 2026-03-14 04:52:34.306589093 +0000 UTC m=+219.951514470
# Command: skyramp generate contract rest http://localhost:8000/items/1 \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output test_items_delete_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 204 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /items/1 DELETE
def test_endpoint_1_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_1_DELETE_response = client.send_request(
        url=URL,
        path="/items/1",
        method="DELETE",
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_endpoint_1_delete()
