# Generated by Skyramp v1.3.12 on 2026-03-14 04:52:34.506503891 +0000 UTC m=+220.151429268
# Command: skyramp generate fuzz rest http://localhost:8000/items/1 \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output test_items_delete_fuzz.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /items/1 DELETE
def test_endpoint_1_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_1_DELETE_response = client.send_request(
        url=URL,
        path="/items/1",
        method="DELETE",
        headers=headers,
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_1_delete()
