# Generated by Skyramp v1.3.12 on 2026-03-14 04:53:03.792363019 +0000 UTC m=+249.437288406
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_category_lifecycle.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-category-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "category": "electronics",
        "description": "Testing the category field",
        "name": "Test Electronics Item",
        "price": 49.99,
        "tax": 4.99
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    items_GET_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="GET",
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_GET_response.status_code == 200

    # Request Body
    items_PUT_request_body = r'''{
        "category": "clothing",
        "description": "Updated to clothing category",
        "name": "Trendy Jacket",
        "price": 79.99,
        "tax": 7.99
    }'''
    
    # Execute Request
    items_PUT_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="PUT",
        body=items_PUT_request_body,
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_PUT_response.status_code == 200

    # Execute Request
    items_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="DELETE",
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
